// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManagement.Infrastructure.Data;

#nullable disable

namespace TaskManagement.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskManagement.Domain.Entities.Label", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("Color").IsRequired().HasMaxLength(7).HasColumnType("nvarchar(7)");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<bool>("IsActive").ValueGeneratedOnAdd().HasColumnType("bit").HasDefaultValue(true);
                    b.Property<string>("Name").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.HasIndex("Name").IsUnique();
                    b.ToTable("Labels", (string)null);
                });

            modelBuilder.Entity("TaskManagement.Domain.Entities.LabelRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<string>("Reason").HasMaxLength(200).HasColumnType("nvarchar(200)");
                    b.Property<int>("RequestedByUserId").HasColumnType("int");
                    b.Property<string>("RequestedName").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                    b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.HasIndex("RequestedByUserId");
                    b.HasIndex("Status");
                    b.ToTable("LabelRequests", (string)null);
                });

            modelBuilder.Entity("TaskManagement.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<bool>("IsRead").ValueGeneratedOnAdd().HasColumnType("bit").HasDefaultValue(false);
                    b.Property<string>("Message").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
                    b.Property<int?>("TaskItemId").HasColumnType("int");
                    b.Property<int>("Type").HasColumnType("int");
                    b.Property<int>("UserId").HasColumnType("int");
                    b.HasKey("Id");
                    b.HasIndex("TaskItemId");
                    b.HasIndex("UserId", "IsRead");
                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("TaskManagement.Domain.Entities.RecurringTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<int>("CreatedByUserId").HasColumnType("int");
                    b.Property<int>("DefaultStatusId").HasColumnType("int");
                    b.Property<string>("Description").HasMaxLength(4000).HasColumnType("nvarchar(4000)");
                    b.Property<bool>("ExcludeHolidays").HasColumnType("bit");
                    b.Property<bool>("ExcludeWeekends").HasColumnType("bit");
                    b.Property<int>("Frequency").HasColumnType("int");
                    b.Property<TimeSpan>("GenerationTime").HasColumnType("time");
                    b.Property<bool>("IsActive").ValueGeneratedOnAdd().HasColumnType("bit").HasDefaultValue(true);
                    b.Property<int?>("DayOfMonth").HasColumnType("int");
                    b.Property<int>("Priority").HasColumnType("int");
                    b.Property<string>("Title").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");
                    b.Property<string>("WeekDays").HasMaxLength(50).HasColumnType("nvarchar(50)");
                    b.HasKey("Id");
                    b.HasIndex("CreatedByUserId");
                    b.HasIndex("DefaultStatusId");
                    b.HasIndex("GenerationTime");
                    b.HasIndex("IsActive");
                    b.ToTable("RecurringTemplates", (string)null);
                });

            modelBuilder.Entity("TaskManagement.Domain.Entities.RecurringTemplateAssignee", b =>
                {
                    b.Property<int>("RecurringTemplateId").HasColumnType("int");
                    b.Property<int>("UserId").HasColumnType("int");
                    b.HasKey("RecurringTemplateId", "UserId");
                    b.HasIndex("UserId");
                    b.ToTable("RecurringTemplateAssignees", (string)null);
                });

            modelBuilder.Entity("TaskManagement.Domain.Entities.RecurringTemplateLabel", b =>
                {
                    b.Property<int>("RecurringTemplateId").HasColumnType("int");
                    b.Property<int>("LabelId").HasColumnType("int");
                    b.HasKey("RecurringTemplateId", "LabelId");
                    b.HasIndex("LabelId");
                    b.ToTable("RecurringTemplateLabels", (string)null);
                });

            modelBuilder.Entity("TaskManagement.Domain.Entities.RecurringTemplateShare", b =>
                {
                    b.Property<int>("RecurringTemplateId").HasColumnType("int");
                    b.Property<int>("UserId").HasColumnType("int");
                    b.HasKey("RecurringTemplateId", "UserId");
                    b.HasIndex("UserId");
                    b.ToTable("RecurringTemplateShares", (string)null);
                });

            modelBuilder.Entity("TaskManagement.Domain.Entities.TaskAssignee", b =>
                {
                    b.Property<int>("TaskItemId").HasColumnType("int");
                    b.Property<int>("UserId").HasColumnType("int");
                    b.Property<DateTime>("AssignedAt").HasColumnType("datetime2");
                    b.HasKey("TaskItemId", "UserId");
                    b.HasIndex("UserId");
                    b.ToTable("TaskAssignees", (string)null);
                });

            modelBuilder.Entity("TaskManagement.Domain.Entities.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<int>("CreatedByUserId").HasColumnType("int");
                    b.Property<string>("Description").HasMaxLength(4000).HasColumnType("nvarchar(4000)");
                    b.Property<DateTime?>("DueDate").HasColumnType("datetime2");
                    b.Property<bool>("IsRecurring").ValueGeneratedOnAdd().HasColumnType("bit").HasDefaultValue(false);
                    b.Property<int?>("ParentTaskId").HasColumnType("int");
                    b.Property<int>("Priority").HasColumnType("int");
                    b.Property<int?>("RecurringTemplateId").HasColumnType("int");
                    b.Property<int>("StatusId").HasColumnType("int");
                    b.Property<string>("Title").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.HasIndex("CreatedByUserId");
                    b.HasIndex("DueDate");
                    b.HasIndex("ParentTaskId");
                    b.HasIndex("StatusId");
                    b.ToTable("TaskItems", (string)null);
                });

            modelBuilder.Entity("TaskManagement.Domain.Entities.TaskLabel", b =>
                {
                    b.Property<int>("TaskItemId").HasColumnType("int");
                    b.Property<int>("LabelId").HasColumnType("int");
                    b.HasKey("TaskItemId", "LabelId");
                    b.HasIndex("LabelId");
                    b.ToTable("TaskLabels", (string)null);
                });

            modelBuilder.Entity("TaskManagement.Domain.Entities.TaskShare", b =>
                {
                    b.Property<int>("TaskItemId").HasColumnType("int");
                    b.Property<int>("UserId").HasColumnType("int");
                    b.HasKey("TaskItemId", "UserId");
                    b.HasIndex("UserId");
                    b.ToTable("TaskShares", (string)null);
                });

            modelBuilder.Entity("TaskManagement.Domain.Entities.TaskStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("Color").IsRequired().HasMaxLength(7).HasColumnType("nvarchar(7)");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<int>("DisplayOrder").HasColumnType("int");
                    b.Property<bool>("IsActive").ValueGeneratedOnAdd().HasColumnType("bit").HasDefaultValue(true);
                    b.Property<string>("Name").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.HasIndex("Name").IsUnique();
                    b.ToTable("TaskStatuses", (string)null);
                    b.HasData(
                        new { Id = 1, Color = "#9E9E9E", CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), DisplayOrder = 1, IsActive = true, Name = "未着手", UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc) },
                        new { Id = 2, Color = "#2196F3", CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), DisplayOrder = 2, IsActive = true, Name = "進行中", UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc) },
                        new { Id = 3, Color = "#FF9800", CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), DisplayOrder = 3, IsActive = true, Name = "レビュー中", UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc) },
                        new { Id = 4, Color = "#F44336", CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), DisplayOrder = 4, IsActive = true, Name = "保留", UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc) },
                        new { Id = 5, Color = "#4CAF50", CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), DisplayOrder = 5, IsActive = true, Name = "完了", UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc) });
                });

            modelBuilder.Entity("TaskManagement.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<string>("DisplayName").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.Property<bool>("IsActive").ValueGeneratedOnAdd().HasColumnType("bit").HasDefaultValue(true);
                    b.Property<string>("LoginId").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                    b.Property<string>("PasswordHash").IsRequired().HasMaxLength(256).HasColumnType("nvarchar(256)");
                    b.Property<int>("Role").HasColumnType("int");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.HasIndex("LoginId").IsUnique();
                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("TaskManagement.Domain.Entities.LabelRequest", b =>
                {
                    b.HasOne("TaskManagement.Domain.Entities.User", "RequestedBy")
                        .WithMany().HasForeignKey("RequestedByUserId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.Navigation("RequestedBy");
                });

            modelBuilder.Entity("TaskManagement.Domain.Entities.Notification", b =>
                {
                    b.HasOne("TaskManagement.Domain.Entities.TaskItem", "TaskItem")
                        .WithMany().HasForeignKey("TaskItemId").OnDelete(DeleteBehavior.SetNull);
                    b.HasOne("TaskManagement.Domain.Entities.User", "User")
                        .WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("TaskItem");
                    b.Navigation("User");
                });

            modelBuilder.Entity("TaskManagement.Domain.Entities.RecurringTemplate", b =>
                {
                    b.HasOne("TaskManagement.Domain.Entities.TaskStatus", "DefaultStatus")
                        .WithMany().HasForeignKey("DefaultStatusId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.HasOne("TaskManagement.Domain.Entities.User", "CreatedBy")
                        .WithMany().HasForeignKey("CreatedByUserId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.Navigation("CreatedBy");
                    b.Navigation("DefaultStatus");
                });

            modelBuilder.Entity("TaskManagement.Domain.Entities.RecurringTemplateAssignee", b =>
                {
                    b.HasOne("TaskManagement.Domain.Entities.RecurringTemplate", "Template")
                        .WithMany("Assignees").HasForeignKey("RecurringTemplateId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("TaskManagement.Domain.Entities.User", "User")
                        .WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.Navigation("Template");
                    b.Navigation("User");
                });

            modelBuilder.Entity("TaskManagement.Domain.Entities.RecurringTemplateLabel", b =>
                {
                    b.HasOne("TaskManagement.Domain.Entities.Label", "Label")
                        .WithMany().HasForeignKey("LabelId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.HasOne("TaskManagement.Domain.Entities.RecurringTemplate", "Template")
                        .WithMany("Labels").HasForeignKey("RecurringTemplateId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Label");
                    b.Navigation("Template");
                });

            modelBuilder.Entity("TaskManagement.Domain.Entities.RecurringTemplateShare", b =>
                {
                    b.HasOne("TaskManagement.Domain.Entities.RecurringTemplate", "Template")
                        .WithMany("Shares").HasForeignKey("RecurringTemplateId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("TaskManagement.Domain.Entities.User", "User")
                        .WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.Navigation("Template");
                    b.Navigation("User");
                });

            modelBuilder.Entity("TaskManagement.Domain.Entities.TaskAssignee", b =>
                {
                    b.HasOne("TaskManagement.Domain.Entities.TaskItem", "TaskItem")
                        .WithMany("Assignees").HasForeignKey("TaskItemId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("TaskManagement.Domain.Entities.User", "User")
                        .WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.Navigation("TaskItem");
                    b.Navigation("User");
                });

            modelBuilder.Entity("TaskManagement.Domain.Entities.TaskItem", b =>
                {
                    b.HasOne("TaskManagement.Domain.Entities.User", "CreatedBy")
                        .WithMany().HasForeignKey("CreatedByUserId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.HasOne("TaskManagement.Domain.Entities.TaskItem", "ParentTask")
                        .WithMany("SubTasks").HasForeignKey("ParentTaskId").OnDelete(DeleteBehavior.Restrict);
                    b.HasOne("TaskManagement.Domain.Entities.TaskStatus", "Status")
                        .WithMany().HasForeignKey("StatusId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.Navigation("CreatedBy");
                    b.Navigation("ParentTask");
                    b.Navigation("Status");
                });

            modelBuilder.Entity("TaskManagement.Domain.Entities.TaskLabel", b =>
                {
                    b.HasOne("TaskManagement.Domain.Entities.Label", "Label")
                        .WithMany().HasForeignKey("LabelId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.HasOne("TaskManagement.Domain.Entities.TaskItem", "TaskItem")
                        .WithMany("TaskLabels").HasForeignKey("TaskItemId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Label");
                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("TaskManagement.Domain.Entities.TaskShare", b =>
                {
                    b.HasOne("TaskManagement.Domain.Entities.TaskItem", "TaskItem")
                        .WithMany("Shares").HasForeignKey("TaskItemId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("TaskManagement.Domain.Entities.User", "User")
                        .WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.Navigation("TaskItem");
                    b.Navigation("User");
                });

            modelBuilder.Entity("TaskManagement.Domain.Entities.RecurringTemplate", b =>
                {
                    b.Navigation("Assignees");
                    b.Navigation("Labels");
                    b.Navigation("Shares");
                });

            modelBuilder.Entity("TaskManagement.Domain.Entities.TaskItem", b =>
                {
                    b.Navigation("Assignees");
                    b.Navigation("Shares");
                    b.Navigation("SubTasks");
                    b.Navigation("TaskLabels");
                });
#pragma warning restore 612, 618
        }
    }
}
